include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v16.0.0-beta.10

variables:
  AUTO_DEVOPS_RELEASE_AUTO: "true"
  AUTO_DEVOPS_PRODUCTION_AUTO: "/^v[0-9]+\\.[0-9]+\\.[0-9]+$/"
